name = "PiecewiseAffineApprox"
uuid = "bc5b63fc-d94a-42ea-9f3c-2beb293a2178"
authors = ["Truls Flatberg <Truls.Flatberg@sintef.no>, Lars Hellemo <Lars.Hellemo@sintef.no>, Thiago Silva <Thiago.Silva.sintef.no>"]
version = "0.3.5"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
PlotsExt = "Plots"
GLMakieExt = "GLMakie"

[compat]
Combinatorics = "1"
Distributions = "0.25"
JuMP = "1"
julia = "^1.9"
